version: '3.8'

services:
  postgres:
    image: postgres:14
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pich
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: